nalej/public-api

- Gopkg.lock
- Gopkg.toml
- cmd/public-api-cli/commands/clusters.go
- components/public-api/mngtcluster/public-api.configmap.yaml
- internal/app/cli/provision.go
- internal/pkg/entities/validator.go
- internal/pkg/server/clusters/handler.go
- internal/pkg/server/clusters/manager.go
* Provide a new command `cluster scale` to scale application clusters.
* Update the configmap to enable nalej admins to scale a cluster.
- [NP-2232](https://nalej.atlassian.net/browse/NP-2232)
> NP-2232 Scale cluster operation

- Gopkg.lock
- Gopkg.toml
- cmd/public-api-cli/commands/unified-logging.go
- internal/pkg/entities/conversions.go
- internal/pkg/server/unified-logging/handler.go
- set `includeMetadata` to true in `unified_logging.Search` method
- update protos to fix a bug in `unified_logging.Search` endpoint
- [NP-2358](https://nalej.atlassian.net/browse/NP-2358)
> NP-2358 set includeMetadata to true in search method

- Gopkg.lock
- Gopkg.toml
- cmd/public-api-cli/commands/clusters.go
- components/public-api/mngtcluster/public-api.configmap.yaml
- internal/app/cli/clusters.go
- internal/app/cli/provision.go
- internal/pkg/entities/conversions.go
- internal/pkg/entities/validator.go
- internal/pkg/server/clusters/handler.go
- internal/pkg/server/clusters/manager.go
* Add two new commands to uninstall and decommission application clusters.
* Overall command refactoring will be done in other PR
Two new fronts are opened in this PR. First, argument renaming in the command help as arguments that are mandatory should be shown as `<arg>`. And secondly, introduction of command help with per command examples.
- [NP-2401](https://nalej.atlassian.net/browse/NP-2401)
> NP-2401 Add cluster uninstall and decomission

- Gopkg.lock
- Gopkg.toml
- internal/app/cli/table.go
- internal/pkg/entities/conversions.go
- internal/pkg/server/clusters/handler.go
- internal/pkg/server/clusters/manager.go
* Update the OpResponse message with the latest version.
- [NP-2401](https://nalej.atlassian.net/browse/NP-2401)
> NP-2401 Update OpResponse to include new fields

- Gopkg.lock
- Gopkg.toml
- internal/app/cli/table.go
- internal/app/cli/unified-logging.go
- internal/pkg/entities/conversions.go
- internal/pkg/server/decorators/common.go
- internal/pkg/server/decorators/sorting_decorator.go
- internal/pkg/server/monitoring/manager.go
- internal/pkg/server/unified-logging/handler.go
- internal/pkg/server/unified-logging/manager.go
- The search method returns `application_manager.LogResponse`
- Fixes a bug in monitoring
- Fixes a bug when creating SearchRequest
- [NP-2435](https://nalej.atlassian.net/browse/NP-2435)
> NP-2435 search with catalog

- cmd/public-api-cli/commands/unified-logging.go
- cmd/public-api-cli/commands/variables.go
- internal/app/cli/table.go
- internal/app/cli/unified-logging.go
- internal/pkg/server/unified-logging/manager.go
Implements --follow in `Unified-logging.Search` function
the `timestamp` has a precision of second, we have to change the precision because we can lose many logs
- [NP-2360](https://nalej.atlassian.net/browse/NP-2360)
> NP-2360 auto log info

- internal/app/cli/unified-logging.go
Uses golang ticker in the search loop
- [NP-2360](https://nalej.atlassian.net/browse/NP-2360)
> NP-2360 Improve search loop

- internal/app/cli/table.go
FIx a bug when writing times
- [NP-XXX](https://nalej.atlassian.net/browse/NP-XXX)
> NP-XX fix a bug when writing times

- internal/app/cli/unified-logging.go
increments 1 millisecond in the --follow loop in the search method  
- [NP-XXX](https://nalej.atlassian.net/browse/NP-XXX)
> NP- xx fix a bug in --follow option

- cmd/public-api-cli/commands/monitoring.go
- internal/app/cli/monitoring.go
Adds a `-w` flag to the `get organization stats` command.
- [NP-2388](https://nalej.atlassian.net/browse/NP-2388)
> NP-2388 Add a watch flag.

- Gopkg.lock
- Gopkg.toml
- cmd/public-api-cli/commands/unified-logging.go
- cmd/public-api-cli/commands/variables.go
- internal/app/cli/unified-logging.go
- internal/pkg/entities/conversions.go
nFirst flag added in the search command; this flag identifies whether the user expects to receive the first n results or not
- [NP-2498](https://nalej.atlassian.net/browse/NP-2498)
> NP-2498 --nFirst flag added

- Gopkg.lock
- Gopkg.toml
- cmd/public-api-cli/commands/unified-logging.go
- cmd/public-api-cli/commands/variables.go
- cmd/public-api/commands/run.go
- components/public-api/mngtcluster/public-api.configmap.yaml
- components/public-api/mngtcluster/public-api.deployment.yaml
- internal/app/cli/table.go
- internal/app/cli/unified-logging.go
- internal/pkg/entities/conversions.go
- internal/pkg/entities/validator.go
- internal/pkg/server/config.go
- internal/pkg/server/service.go
- internal/pkg/server/unified-logging/handler.go
- internal/pkg/server/unified-logging/handler_it_test.go
- internal/pkg/server/unified-logging/manager.go
Implements Download message
Adds new command in public-api-cli
````
public-api-cli log download --help
````
The download of the cli should wait for the file to be generated and download it. As the rest of the functionalities are implemented, they will be added. For now, just calls to download to generate the zip file
executing 
````
public-api-cli log download 
````
- [NP-2480](https://nalej.atlassian.net/browse/NP-2480)
> NP-2480 Download implemented

- cmd/public-api-cli/commands/unified-logging.go
- internal/app/cli/table.go
- internal/app/cli/unified-logging.go
- adds check command
- include calls to check method in the download command
check:
````
public-api-cli log check [requestId]
````
download:
````
public-api-cli log download
````
- [NP-2501](https://nalej.atlassian.net/browse/NP-2501)
> NP-2501 the download command calls to check method

- cmd/public-api-cli/commands/unified-logging.go
- internal/app/cli/unified-logging.go
includes download commands:
````
Download application logs based on application and service group instance
Usage:
public-api-cli log download [flags]
public-api-cli log download [command]
Available Commands:
check       Check the status of a download request
get         Get results file
search      Search and download log entries
Flags:
-h, --help   help for download
Global Flags:
--cacert string           Path of the CA certificate to validate the server connection
--consoleLogging          Pretty print logging
--debug                   Set debug level
--insecure                Skip CA validation when connecting to a secure TLS server
--nalejAddress string     Address (host) of the Nalej platform
--organizationID string   Organization identifier
--useTLS                  Connect to a TLS …
```
> NP-2484 download commands added

- cmd/public-api-cli/commands/unified-logging.go
- internal/app/cli/table.go
- internal/app/cli/unified-logging.go
-w flag included in `log download list` command
Executing
````
public-api-cli log download list -w
````
and while ask for  downloads and check these operations are showing
- [NP-2503](https://nalej.atlassian.net/browse/NP-2503)
> NP-2503 -watch flag added in list command

- cmd/public-api-cli/commands/clusters.go
added default cluster type (KUBERNETES) and target platform (MINIKUBE)
- [NP-2513](https://nalej.atlassian.net/browse/NP-2513)
> NP-2513 added default cluster type and target platform

- Gopkg.lock
- Gopkg.toml
- cmd/public-api-cli/commands/organization.go
- cmd/public-api-cli/commands/variables.go
- cmd/public-api/commands/run.go
- components/public-api/mngtcluster/public-api.configmap.yaml
- components/public-api/mngtcluster/public-api.deployment.yaml
- internal/app/cli/organizations.go
- internal/app/cli/table.go
- internal/pkg/entities/validator.go
- internal/pkg/server/applications/handler_it_test.go
- internal/pkg/server/clusters/handler_it_test.go
- internal/pkg/server/config.go
- internal/pkg/server/devices/handler_it_test.go
- internal/pkg/server/ithelpers/helpers.go
- internal/pkg/server/nodes/handler_it_test.go
- internal/pkg/server/organizations/handler.go
- internal/pkg/server/organizations/handler_it_test.go
- internal/pkg/server/organizations/manager.go
- internal/pkg/server/resources/handler_it_test.go
- internal/pkg/server/roles/handler_it_test.go
- internal/pkg/server/service.go
- internal/pkg/server/unified-logging/handler_it_test.go
- internal/pkg/server/users/handler_it_test.go
- connects to organization-manager through which it performs all organization operations
- updates the Organization entity adding the new fields.
- updates the results showed in the organization info command
- implements a new command to update the organization
Photo update
- Info command, executing 
```
./bin/public-api-cli org info
ID                                     NAME
e44dbc6c-df58-41e2-9810-a788fcbe4f5a   Nalej Lab Spain
ADDRESS                     CITY     STATE    COUNTRY   ZIP CODE
Paseo de la Castellana 77   Madrid   Madrid   Spain     28046
NUM.USERS   NUM.ROLES   NUM.SETTINGS
3           4           0
```
- Update command: 
```
./bin/public-api-cli org update --help
org update --help
Update the info of an organization
Usage:
public-api-cli organization update [flags] …
```
> NP-2524 public-api connects to organization-manager

- Gopkg.lock
- Gopkg.toml
- cmd/public-api-cli/commands/organization.go
- internal/app/cli/organizations.go
- internal/pkg/entities/validator.go
- internal/pkg/server/decorators/common.go
- internal/pkg/server/decorators/sorting_decorator.go
- internal/pkg/server/organization-settings/handler.go
- internal/pkg/server/organization-settings/manager.go
- implements the sort decorator for setting list.
- adds a flag to sort in list setting command
executing the list with the sort flag and without it and checking the results are ordered as required
- Ascending
```
./bin/public-api-cli org set list
```
```
KEY    VALUE        DESCRIPTION
key0   value0       description
key1   new update   description
key2   value2       description
```
- Descending
```
./bin/public-api-cli org set list --desc
```
```
KEY    VALUE        DESCRIPTION
key2   value2       description
key1   new update   description
key0   value0       description
```
- [NP-2540](https://nalej.atlassian.net/browse/NP-2540)
> NP-2540 Sort decorator implemented for Setting list

- Gopkg.lock
- Gopkg.toml
- cmd/public-api-cli/commands/clusters.go
- components/public-api/mngtcluster/public-api.configmap.yaml
- internal/app/cli/provision.go
- internal/pkg/entities/validator.go
- internal/pkg/server/clusters/handler.go
- internal/pkg/server/clusters/manager.go
Fix typo in decommission word.
- [NP-2448](https://nalej.atlassian.net/browse/NP-2448)
> NP-2448 fix decommission typo

- Gopkg.lock
- Gopkg.toml
- cmd/public-api-cli/commands/organization.go
- internal/app/cli/organizations.go
- internal/app/cli/table.go
- internal/pkg/entities/validator.go
**NOTE**: This PR depends on [this other one (organization-manager)](https://github.com/nalej/organization-manager/pull/5).
Add the email to the organization as a mandatory field. Here will be optional until cluster creation scripts are updated accordingly.
- [NP-2616](https://nalej.atlassian.net/browse/NP-2616)
> NP-2616 add org email as mandatory

- Gopkg.lock
- cmd/public-api-cli/commands/users.go
- cmd/public-api-cli/commands/variables.go
- internal/pkg/entities/validator.go
**NOTE** This PR depends on [this other one (user-manager)](https://github.com/nalej/user-manager/pull/31).
Include new user required fields.
- [NP-2534](https://nalej.atlassian.net/browse/NP-2534)
> NP-2534 user required fields

- cmd/public-api-cli/commands/clusters.go
- cmd/public-api-cli/commands/variables.go
- internal/app/cli/clusters.go
- internal/pkg/entities/validator.go
- internal/pkg/server/clusters/handler_it_test.go
- internal/pkg/server/clusters/manager.go
- internal/pkg/server/decorators/sorting_decorator.go
- internal/pkg/server/service.go
- internal/pkg/server/users/manager.go
updates public-api-cli to allow to modify the name of a cluster
- [NP-2629](https://nalej.atlassian.net/browse/NP-2629)
> NP-2629 update cluster name
